# Generated by Django 3.0.8 on 2020-07-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/testimage.jpg', upload_to='images/products', verbose_name='상품 이미지'),
        ),
    ]
